services:
    livechat:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: livechat-server
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - LIVECHAT_PORT=${LIVECHAT_PORT}
            - TOKEN=${TOKEN}
            - TENOR_API_KEY=${TENOR_API_KEY}
            - GIPHY_API_KEY=${GIPHY_API_KEY}
            - DOMAIN=${DOMAIN}
        ports:
            - '5000:5000'
        volumes:
            - ./logs:/app/logs
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2G
                reservations:
                    cpus: '1'
                    memory: 1G
