services:
    livechat:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: livechat-server
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - ENVIRONMENT=RELEASE
            - LIVECHAT_PORT=${LIVECHAT_PORT}
            - TOKEN=${TOKEN}
            - WEBHOOK_URL=${WEBHOOK_URL}
        ports:
            - '4000:4000'
        volumes:
            - ./logs:/app/logs
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2G
                reservations:
                    cpus: '1'
                    memory: 1G
            #healthcheck:
            #test: curl --fail http://localhost:4000/ || exit 1
            #interval: 60s
            #timeout: 30s
            #retries: 3
            #start_period: 60s
